name: denari_mobile
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_core: ^1.18.0
  flow_builder: ^0.0.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^9.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  meta: ^1.3.0
  plaid_flutter: ^2.2.2
  syncfusion_flutter_charts: ^20.1.59
  very_good_analysis: ^2.4.0

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  bloc: ^8.0.2
  bloc_test: ^9.0.2
  flutter_bloc: ^8.0.1
