// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMFU_0BB5WAJ_3O71b1JjtyxVn_w6NMuk',
    appId: '1:738409808827:web:8237d2cde9d342ccf13a9e',
    messagingSenderId: '738409808827',
    projectId: 'denari-app',
    authDomain: 'denari-app.firebaseapp.com',
    storageBucket: 'denari-app.appspot.com',
    measurementId: 'G-BY3DJY5JPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT9_i-uUWWF7Cm_aYkoesjcYW45cxwj98',
    appId: '1:738409808827:android:dab7fac3da222708f13a9e',
    messagingSenderId: '738409808827',
    projectId: 'denari-app',
    storageBucket: 'denari-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeK1nxWeRJ9soqQ0o15_JAjhUpfh0vu3U',
    appId: '1:738409808827:ios:422c653139239d61f13a9e',
    messagingSenderId: '738409808827',
    projectId: 'denari-app',
    storageBucket: 'denari-app.appspot.com',
    iosClientId: '738409808827-1nkmf88k9ga4fqjp86rvqluimjllnoeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.denariMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeK1nxWeRJ9soqQ0o15_JAjhUpfh0vu3U',
    appId: '1:738409808827:ios:422c653139239d61f13a9e',
    messagingSenderId: '738409808827',
    projectId: 'denari-app',
    storageBucket: 'denari-app.appspot.com',
    iosClientId: '738409808827-1nkmf88k9ga4fqjp86rvqluimjllnoeh.apps.googleusercontent.com',
    iosBundleId: 'com.example.denariMobile',
  );
}
